<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="56605" started-at="2022-03-10T12:55:04Z" finished-at="2022-03-10T12:56:01Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="56605" started-at="2022-03-10T12:55:04Z" finished-at="2022-03-10T12:56:01Z">
      <class name="technocredits.screenShotCode.CapatureScreenShot">
        <test-method status="FAIL" signature="capatureScreenShot()[pri:0, instance:technocredits.screenShotCode.CapatureScreenShot@548e7350]" name="capatureScreenShot" duration-ms="42016" started-at="2022-03-10T18:25:04Z" finished-at="2022-03-10T18:25:46Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at technocredits.screenShotCode.CapatureScreenShot.capatureScreenShot(CapatureScreenShot.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- capatureScreenShot -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:technocredits.screenShotCode.CapatureScreenShot@548e7350]" name="afterMethod" is-config="true" duration-ms="14418" started-at="2022-03-10T18:25:46Z" finished-at="2022-03-10T18:26:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=capatureScreenShot status=FAILURE method=CapatureScreenShot.capatureScreenShot()[pri:0, instance:technocredits.screenShotCode.CapatureScreenShot@548e7350] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- technocredits.screenShotCode.CapatureScreenShot -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
